#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol/tprotocol'

class GetResult
  include ThriftStruct
  attr_accessor :context, :results
  FIELDS = {
    1 => {:type => TType::STRING, :name => 'context'},
    2 => {:type => TType::LIST, :name => 'results', :element => {:type => TType::STRING}}
  }
end

class FailureException < StandardError
  include ThriftStruct
  def initialize(message=nil)
    super()
    self.message = message
  end

  attr_accessor :message
  FIELDS = {
    1 => {:type => TType::STRING, :name => 'message'}
  }
end

